export const companyImportFieldLabels: Record<string, string> = {
    cnpj: 'CNPJ',
    razao_social: 'Razão Social',
    nome_fantasia: 'Nome Fantasia',
    logradouro: 'Logradouro',
    numero: 'Número',
    complemento: 'Complemento',
    bairro: 'Bairro',
    cep: 'CEP',
    uf: 'UF',
    city_name: 'Município',
    matriz_filial: 'Matriz/Filial',
    ente_federativo: 'Ente Federativo',
    cnae_code: 'CNAE Principal (código)',
    legal_nature_code: 'Natureza Jurídica (código)',
    data_inicio_atividade: 'Data de Início da Atividade',
    company_size: 'Porte',
    share_capital: 'Capital Social',
    is_mei: 'Optante MEI',
    mei_entry_date: 'Data de Opção pelo MEI',
    mei_exit_date: 'Data de Exclusão do MEI',
    registration_status: 'Situação Cadastral',
    registration_status_date: 'Data da Situação Cadastral',
    tax_regime: 'Regime Tributário',
    estimated_revenue_value: 'Faturamento Estimado',
    employee_count: 'Quantidade de Funcionários',
    active_federal_debt: 'Dívida Ativa Federal',
    total_debt: 'Dívida Total',
    site: 'Site',
    contact_phone: 'Telefone',
    contact_email: 'E-mail',
    contact_whatsapp: 'WhatsApp',
};
